/* ============================================================
TABLE users
Chaque utilisateur possède un compte avec username + password
============================================================ */
CREATE TABLE
  users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID unique du user
    created_at TIMESTAMPTZ DEFAULT NOW (), -- Date de création
    username TEXT NOT NULL, -- Nom d'utilisateur
    password TEXT NOT NULL -- Mot de passe hashé
  );

-- Empêche deux utilisateurs d'avoir le même username
ALTER TABLE users ADD CONSTRAINT unique_username UNIQUE (username);

/* ============================================================
TABLE shopping_lists
Une seule liste par utilisateur
============================================================ */
CREATE TABLE
  shopping_lists (
    id SERIAL PRIMARY KEY, -- ID unique de la liste
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- À quel user appartient la liste
    name VARCHAR NOT NULL, -- Nom de la liste
    created_at TIMESTAMPTZ DEFAULT NOW () -- Date de création
  );

-- Empêche un utilisateur d'avoir plusieurs listes
ALTER TABLE shopping_lists ADD CONSTRAINT unique_user_list UNIQUE (user_id);

/* ============================================================
TABLE products
Produits appartenant à une liste
Un produit = un nom unique par liste
(ex: un user ne peut avoir qu'une seule "tomate")
============================================================ */
CREATE TABLE
  products (
    id SERIAL PRIMARY KEY,
    list_id INT NOT NULL REFERENCES shopping_lists (id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    to_buy BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW ()
  );

ALTER TABLE products ADD CONSTRAINT unique_product_per_list UNIQUE (list_id, name);

CREATE TABLE sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_sessions_user_id
ON sessions (user_id);